// This file is auto-generated from Solidity source files. Do not edit manually.
// Generated by: bun run script/parse-events.ts

export const CONTRACT_EVENT_MAP = {
  AccountGate: {
    Bridge: {
      hash: '0x7aa5ae620294318af92bf4e2b2a729646c932a80312a5fa630da993a2ef5cc10',
      args: [{type:"tuple",name:"intent",components:[{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"uint256",name:"blockNumber"},{type:"uint256",name:"deadline"},{type:"uint256",name:"acceptableRelayFee"},{type:"uint256",name:"nonce"},{type:"uint256",name:"chainId"},{type:"bytes32",name:"tokenId"},{type:"address",name:"provider"},{type:"bytes",name:"providerCallData"},{type:"uint256",name:"inputAmount"},{type:"uint256",name:"outputAmount"},{type:"uint256",name:"destinationChainId"},{type:"uint32",name:"expires"},{type:"uint32",name:"fillDeadline"}]},{type:"address",name:"account"}]
    },
    Recognize: {
      hash: '0x7709d2e247ded521a3d8b6d76ec26284fdd5df4413db1c22519a5ba3029aecbe',
      args: [{type:"tuple",name:"intent",components:[{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"uint256",name:"blockNumber"},{type:"uint256",name:"deadline"},{type:"uint256",name:"acceptableRelayFee"},{type:"uint256",name:"nonce"},{type:"uint256",name:"chainId"},{type:"bytes32",name:"tokenId"},{type:"uint256",name:"amount"}]},{type:"address",name:"account"}]
    }
  },
  AccountModule: {
    AccountCall: {
      hash: '0xc7f71329056affdda370fc48fc59028fdfa01533125a5a6931832e160270f66a',
      args: [{type:"uint256",name:"chainId"},{type:"address",name:"account"},{type:"uint256",name:"nonce"},{type:"tuple[]",name:"transferList",components:[{type:"bytes32",name:"tokenId"},{type:"address",name:"token"},{type:"uint256",name:"amountIn"},{type:"uint256",name:"amountOut"}]},{type:"uint256[]",name:"signedPostBalanceList"},{type:"uint256[]",name:"postBalanceList"}]
    },
    DeployFundAccount: {
      hash: '0x58d9c1e134c3725e0aafe460d7e043deaeee5c5393e8507bef8289ffc86225ff',
      args: [{type:"address",name:"signer"},{type:"address",name:"account"},{type:"address",name:"route"}]
    },
    DeployPuppetAccount: {
      hash: '0x7eb7e993a5f78384ea2bc550a06f6bbd0c81bf1dd87e41d93f83db79a5b213a6',
      args: [{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"address",name:"account"},{type:"address",name:"route"}]
    },
    MandateCall: {
      hash: '0x6fed18cec7ec1f04eec6b2a4a063be23a15114300daa6c8379022f08e40f4fb7',
      args: [{type:"uint256",name:"chainId"},{type:"address",name:"puppet"},{type:"bytes32",name:"mandateDigest"},{type:"tuple[]",name:"transferList",components:[{type:"bytes32",name:"tokenId"},{type:"address",name:"token"},{type:"uint256",name:"amountIn"},{type:"uint256",name:"amountOut"}]},{type:"uint256[]",name:"signedPostBalanceList"},{type:"uint256[]",name:"postBalanceList"}]
    }
  },
  AllocateModule: {
    Allocate: {
      hash: '0x2d453a8b2eb4888bfee5a5b17781ba95747a5f795cd81b44fe943773178f8d8e',
      args: [{type:"tuple",name:"intent",components:[{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"uint256",name:"blockNumber"},{type:"uint256",name:"deadline"},{type:"uint256",name:"acceptableRelayFee"},{type:"uint256",name:"nonce"},{type:"uint256",name:"chainId"},{type:"tuple",name:"share",components:[{type:"address",name:"master"},{type:"bytes32",name:"baseTokenId"},{type:"bytes32",name:"name"}]},{type:"uint256",name:"acceptableNetAssetValue"},{type:"uint256",name:"totalShareSupply"},{type:"uint256",name:"masterAmount"},{type:"address[]",name:"puppetList"},{type:"uint256[]",name:"matchedAmountList"}]},{type:"address",name:"fundAccount"},{type:"uint256",name:"ownerNewShares"},{type:"uint256[]",name:"puppetSharesMintedList"},{type:"uint256",name:"totalMatched"},{type:"uint256",name:"param"}]
    }
  },
  Dictate: {
    RemoveGate: {
      hash: '0x0794c14053f516eea7b2e26d8561f2fa6a847764b7d48ec4dcc178467e0613d7',
      args: [{type:"uint256",name:"chainId"},{type:"bytes32",name:"name"},{type:"address",name:"proxy"}]
    },
    SetGate: {
      hash: '0x440a897c6ecd953a301575fccbd2a9596ac1797cebdb6de3565abc956d260582',
      args: [{type:"uint256",name:"chainId"},{type:"bytes32",name:"name"},{type:"address",name:"proxy"},{type:"address",name:"impl"},{type:"bytes",name:"config"}]
    },
    UpdateAccess: {
      hash: '0x9f761f589a1dd9a2fa7e2410eab00ca19affc279a092607d4b14e0bf15273d54',
      args: [{type:"uint256",name:"chainId"},{type:"address",name:"target"},{type:"address",name:"user"},{type:"bool",name:"flag"}]
    },
    UpdatePermission: {
      hash: '0xec7b111394fb6c30c991d21122bfa5278cc815991afa5366f36dd972694651b1',
      args: [{type:"uint256",name:"chainId"},{type:"address",name:"target"},{type:"bytes4",name:"selector"},{type:"address",name:"user"},{type:"bool",name:"flag"}]
    }
  },
  HubGate: {
    WithdrawToBridge: {
      hash: '0xdfd02049af371073122fab090ec83dc756ec2df286c997ab945fa39e3cd93dd5',
      args: [{type:"tuple",name:"intent",components:[{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"uint256",name:"blockNumber"},{type:"uint256",name:"deadline"},{type:"uint256",name:"acceptableRelayFee"},{type:"uint256",name:"nonce"},{type:"uint256",name:"chainId"},{type:"bytes32",name:"tokenId"},{type:"address",name:"inputToken"},{type:"address",name:"outputToken"},{type:"uint256",name:"inputAmount"},{type:"uint256",name:"outputAmount"},{type:"uint256",name:"destinationChainId"},{type:"address",name:"provider"},{type:"bytes",name:"providerCallData"},{type:"uint32",name:"expires"},{type:"uint32",name:"fillDeadline"}]},{type:"address",name:"puppetAccount"},{type:"address",name:"recipient"}]
    },
    WithdrawToWallet: {
      hash: '0x68ed3d1b5e751db0939430d855be419fa5d97c12247d546cb2ed796e1e7ab93b',
      args: [{type:"tuple",name:"intent",components:[{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"uint256",name:"blockNumber"},{type:"uint256",name:"deadline"},{type:"uint256",name:"acceptableRelayFee"},{type:"uint256",name:"nonce"},{type:"uint256",name:"chainId"},{type:"bytes32",name:"tokenId"},{type:"uint256",name:"amount"}]},{type:"address",name:"account"}]
    }
  },
  MasterGate: {
    Operate: {
      hash: '0x81fb87d9a5f286238a2fad3da31bb37826bc310f3dae1f4c04560a6367abd806',
      args: [{type:"tuple",name:"intent",components:[{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"uint256",name:"blockNumber"},{type:"uint256",name:"deadline"},{type:"uint256",name:"acceptableRelayFee"},{type:"uint256",name:"nonce"},{type:"uint256",name:"chainId"},{type:"tuple[]",name:"callList",components:[{type:"address",name:"target"},{type:"uint256",name:"value"},{type:"uint256",name:"gasLimit"},{type:"bytes",name:"callData"}]},{type:"tuple[]",name:"transferList",components:[{type:"bytes32",name:"tokenId"},{type:"address",name:"token"},{type:"uint256",name:"amountIn"},{type:"uint256",name:"amountOut"}]}]},{type:"address",name:"account"},{type:"address",name:"sender"},{type:"bytes[]",name:"result"}]
    }
  },
  RedeemModule: {
    Claim: {
      hash: '0x5c2db6855baf6c374b9d0065771a33d4c31a8627d7b9d40f3fc6aa5dbd7b8a48',
      args: [{type:"tuple",name:"intent",components:[{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"uint256",name:"blockNumber"},{type:"uint256",name:"deadline"},{type:"uint256",name:"acceptableRelayFee"},{type:"uint256",name:"nonce"},{type:"uint256",name:"chainId"},{type:"tuple",name:"share",components:[{type:"address",name:"master"},{type:"bytes32",name:"baseTokenId"},{type:"bytes32",name:"name"}]},{type:"uint256",name:"amount"}]},{type:"address",name:"holder"},{type:"address",name:"fund"},{type:"uint256",name:"effective"},{type:"uint256",name:"stake"},{type:"uint256",name:"accruedAfter"},{type:"uint256",name:"accruedPerStake"},{type:"uint256",name:"totalStake"},{type:"uint256",name:"totalShares"}]
    },
    Fulfill: {
      hash: '0xd8a1a2f790da4a22efd81c7bc12290bbad48858d15ac8f2b154956a26fe14e47',
      args: [{type:"tuple",name:"intent",components:[{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"uint256",name:"blockNumber"},{type:"uint256",name:"deadline"},{type:"uint256",name:"acceptableRelayFee"},{type:"uint256",name:"nonce"},{type:"uint256",name:"chainId"},{type:"tuple",name:"share",components:[{type:"address",name:"master"},{type:"bytes32",name:"baseTokenId"},{type:"bytes32",name:"name"}]},{type:"uint256",name:"sharesOut"},{type:"uint256",name:"acceptableNetAssetValue"},{type:"uint256",name:"totalShareSupply"},{type:"uint256",name:"acceptableShares"}]},{type:"address",name:"fund"},{type:"address",name:"baseToken"},{type:"uint256",name:"sharesRetired"},{type:"uint256",name:"drainedBase"},{type:"uint256",name:"accruedPerStake"},{type:"uint256",name:"totalStake"},{type:"uint256",name:"poolShares"},{type:"uint256",name:"param"},{type:"uint256",name:"claimed"}]
    },
    Sell: {
      hash: '0x2960d925d7f3fc57a6fc5d05aac27fd1ae17fcf2a31a901375f427c5224e3219',
      args: [{type:"tuple",name:"intent",components:[{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"uint256",name:"blockNumber"},{type:"uint256",name:"deadline"},{type:"uint256",name:"acceptableRelayFee"},{type:"uint256",name:"nonce"},{type:"uint256",name:"chainId"},{type:"tuple",name:"share",components:[{type:"address",name:"master"},{type:"bytes32",name:"baseTokenId"},{type:"bytes32",name:"name"}]},{type:"uint256",name:"sharesOut"}]},{type:"address",name:"holder"},{type:"address",name:"fund"},{type:"uint256",name:"stake"},{type:"uint256",name:"claimed"},{type:"uint256",name:"cursor"},{type:"uint256",name:"totalStake"},{type:"uint256",name:"param"}]
    }
  },
  RegisterModule: {
    RegisterToken: {
      hash: '0x089c2fdb5de1cfd1599de9bcc6200995e0219f36676cf03b3aa6bafd0d239980',
      args: [{type:"uint256",name:"chainId"},{type:"bytes32",name:"tokenId"},{type:"address",name:"token"},{type:"uint256",name:"cap"},{type:"address",name:"hubToken"}]
    },
    SetWnt: {
      hash: '0x1181d4b817c8938e95b95b84be34f865702adf05db5add8b907c6bfe393627ce',
      args: [{type:"uint256",name:"chainId"},{type:"bytes32",name:"tokenId"},{type:"address",name:"wnt"}]
    }
  },
  ShareModule: {
    CreateShareToken: {
      hash: '0xa2950e4c1878e266c825ab552e11d8d4233bf677b6e5bbd63c70ee00cadb7752',
      args: [{type:"address",name:"fund"},{type:"address",name:"shareToken"},{type:"bytes32",name:"baseTokenId"},{type:"bytes32",name:"name"}]
    }
  },
  SubscribeModule: {
    Subscribe: {
      hash: '0x48d404d629614f23fea65a9948e14b556ebee2cdcec7eb97cad37db32d0f210e',
      args: [{type:"address",name:"puppetAccount"},{type:"address",name:"fund"},{type:"tuple",name:"params",components:[{type:"address",name:"user"},{type:"address",name:"signer"}]},{type:"bytes",name:"body"},{type:"bytes",name:"mandate"}]
    }
  },
  WalletDepositModule: {
    WalletDeposit: {
      hash: '0x1cbf064085552c9d74d0fe872cfdb0e67b75a1864f2b27985ebef118fa15d68f',
      args: [{type:"uint256",name:"chainId"},{type:"address",name:"depositor"},{type:"address",name:"recipient"},{type:"address",name:"token"},{type:"uint256",name:"amount"},{type:"uint256",name:"depositPostBalance"}]
    }
  }
} as const
